### ISSUE TITLE
AOT builds are failiing because of the ngx-chips dependency... I believe the culprit is the version of angular-cli you are using. 

### ISSUE THREAD

**Issue by xtianus79** [Gbuomprisco/ngx-chips#550]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

In my case the bug is manifesting because Angular AOT is run via ngtools/webpack which is the sister of angular-cli which you are using.  So this is what is happening... Because this dependency 
is trying to run its build and AOT upon installing the package i.e. into the dist folder <<< it is running against my webpack config's ngtoosl/webpack installation housing its AOT parameters.  thus causing the AOT build to fail

Below I state recreation steps but the issue is definatelty stemming from how you're building the package upon installation which is using AOT parameters from anguar cli.  

My first thought is... why place this step on the user installing a package... I get if someone wanted to customize the css or files but having this step run alongside of another person's AOT installation and params should / could be thought out better so that this won't occur.  

I stated in another thread here for this package is that AOT ngtools / angular-cli was having issues with one of their dependencies... it was auto incremented through ^ and broke a lot of peoples AOT builds. something with enhanced-resolver...  What's insane is that they did a fixed version and have since then reverted back to allowing ^ increments for minor updates.

I would like to work through this with you as my build depends on it.  

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**

Download an Angular quick repo and use ngtools/webpack inside of it... then install your package and you will see the error.  

**What do you use to build your app?. Please specify the version**

**Angular version:** 

**ngx-chips version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Hi @xtianus79,
thanks for the detailed investigation. I am not sure how else providing an AOT build but to return to the distributed files, the .metadata and the sources themselves. I'll have a further look during the weekend, but if you stumble on a solution feel free to open a PR

**Comment by xtianus79** [comment]
@Gbuomprisco can you tell me the build process flow. I tried to fork the repo and use my forked repo as the npm package but it didn't build the dist directory which leads me to believe this is being done on the during my npm installation.

**Comment by xtianus79** [comment]
@Gbuomprisco also, are you using angular-cli?

**Comment by hakalb** [comment]
@Gbuomprisco Will this issue be solved in the near future?

**Comment by Gbuomprisco** [comment]
Sorry - I'll try in the weekend

**Comment by hakalb** [comment]
Thanks, I appreciate your work with ngx-chips.

**Comment by er-ant** [comment]
Still appears, any changes? May be you will make it in simple angular's module style to provide AoT?

**Comment by Gbuomprisco** [comment]
Check out the very latest, this has been fixed

**Comment by kotmatpockuh** [comment]
still appears...
