### ISSUE TITLE
Need version that doesn't rely on global

### ISSUE THREAD

**Issue by PTC-JoshuaMatthews** [Gbuomprisco/ngx-chips#694]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

ngx-chips.js:933 Uncaught ReferenceError: global is not defined
    at Object.../node_modules/ngx-chips/esm5/ngx-chips.js (ngx-chips.js:933)
    at __webpack_require__ (bootstrap:74)
    at Object../main.ts (environment.ts:19)
    at __webpack_require__ (bootstrap:74)
    at Object.0 (common.service.ts:6)
    at __webpack_require__ (bootstrap:74)
    at checkDeferredModules (bootstrap:43)
    at Array.webpackJsonpCallback [as push] (bootstrap:30)
    at main.js:1

**Expected behavior**

Browser module should not depend on global

**Minimal reproduction of the problem with instructions (if applicable)**

Use @next angular cli to create a project. Install ngx-chips. Import it to a component. Load the project in browser.

**What do you use to build your app?. Please specify the version**

**Angular version:** 

**ngx-chips version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
From what I read this should be solved at the cli side, try downgrading and await the final version

**Comment by PTC-JoshuaMatthews** [comment]
Where did you read that? From what I've seen they removed node globals and don't plan on putting them back.  See https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814

It does say at the end that "some of the issues will be resolved" but doesn't seem like he is referring to putting node globals back in.

**Comment by Gbuomprisco** [comment]
You're right, it doesn't look like they plan on changing that exact thing. I won't be able to publish until the weekend, so I still suggest to downgrade for now

**Comment by PTC-JoshuaMatthews** [comment]
Thanks man! Just wanted to make sure you're still working on it before waiting. You still have the best chip control in the game man! Props to you! I've been watching the material guys attempt to combine input and chips and autocomplete into a similar functionality to no avail so far.

**Comment by PTC-JoshuaMatthews** [comment]
Any chance to look at this over weekend?

**Comment by Gbuomprisco** [comment]
Hi @PTC-JoshuaMatthews, can you check v1.6.8? Thanks
